config/routes.rb
RedCross::Application.routes.draw do
  get "main/display"
  post "main/new"
  get "main/test"

  resources :stock_types

  resources :genders

  resources :notifying_agencies

  resources :incident_stock_types

  resources :ethnicities

  resources :economic_statuses

  resources :dwelling_types

  resources :disaster_types

  resources :staffs

  resources :incident_assistances

  resources :clients

  resources :incidents

  resources :incident_responders

  root :to => 'main#display'
  match 'main/new', :controller => "main", :action => "new", :as => "main_new"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :city, :county, :date_deceased, :date_of_birth, :economic_status_type_id, :ethnicity_type_id, :family_id, :first_name, :gender_type_id, :head_of_house_hold, :home_phone, :language_id, :last_name, :mobile_phone, :postal_code, :salutation, :state, :suffix, :work_phone
end

app/models/disaster_type.rb
class DisasterType < ActiveRecord::Base
  attr_accessible :name
end

app/models/dwelling_type.rb
class DwellingType < ActiveRecord::Base
  attr_accessible :name, :story
end

app/models/economic_status.rb
class EconomicStatus < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :cliend_id
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :type
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  attr_accessible :address_line1, :city, :county, :damange_assessment, :date_follow_up, :dispatcher_id, :dwelling_id, :events_sequence, :follow_up_result, :incident_date, :incident_time, :injuries_or_death, :memo_verification_info, :national_incident_id, :nbr_affected_families, :nbr_affected_individuals, :notification_agency_id, :notification_date, :notification_time, :person_following_up, :postal_code, :rc_chapter, :state, :trainee_follow_up, :trainee_name, :verification_agency, :verification_date, :verification_time
  # has_many :family, :incident_responder, :incident_client, :incident_disaster, :incident_assistance, :staff, :incident_stock_type
end

app/models/incident_client.rb
class IncidentClient < ActiveRecord::Base
  attr_accessible :family_id, :incident_id, :nine01_case_id
  belongs_to :incident
end

app/models/incident_disaster.rb
class IncidentDisaster < ActiveRecord::Base
  attr_accessible :disaster_type_id, :incident_id
  belongs_to :incident
end

app/models/incident_responder.rb
class IncidentResponder < ActiveRecord::Base
  attr_accessible :date_left_scene, :date_on_scene, :dispatched_date, :dispatched_time, :dispatcher_id, :incident_id, :initial_responder, :staff_id, :time_left_scene, :time_on_scene
  belongs_to :incident
end

app/models/notifying_agency.rb
class NotifyingAgency < ActiveRecord::Base
  attr_accessible :name
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :case_worker, :city, :country, :county, :dispatcher, :first_name, :home_phone, :last_name, :latitude, :longitude, :mobile_phone, :postal_code, :responder, :salutation, :state, :suffix, :work_phone
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  attr_accessible :name
  serialize :name, JSON
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staffs }
    end
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
    @staff = Staff.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/new
  # GET /staffs/new.json
  def new
    @staff = Staff.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staff }
    end
  end

  # GET /staffs/1/edit
  def edit
    @staff = Staff.find(params[:id])
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(params[:staff])

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render json: @staff, status: :created, location: @staff }
      else
        format.html { render action: "new" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staffs/1
  # PUT /staffs/1.json
  def update
    @staff = Staff.find(params[:id])

    respond_to do |format|
      if @staff.update_attributes(params[:staff])
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff = Staff.find(params[:id])
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/ethnicities_helper.rb
module EthnicitiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/stock_types_helper.rb
module StockTypesHelper
end

app/views/staffs/_form.html.erb
<%= form_for(@staff) do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :salutation %><br />
    <%= f.text_field :salutation %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :suffix %><br />
    <%= f.text_field :suffix %>
  </div>
  <div class="field">
    <%= f.label :address_line1 %><br />
    <%= f.text_field :address_line1 %>
  </div>
  <div class="field">
    <%= f.label :address_line2 %><br />
    <%= f.text_field :address_line2 %>
  </div>
  <div class="field">
    <%= f.label :address_line3 %><br />
    <%= f.text_field :address_line3 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :responder %><br />
    <%= f.check_box :responder %>
  </div>
  <div class="field">
    <%= f.label :dispatcher %><br />
    <%= f.check_box :dispatcher %>
  </div>
  <div class="field">
    <%= f.label :case_worker %><br />
    <%= f.check_box :case_worker %>
  </div>
  <div class="field">
    <%= f.label :home_phone %><br />
    <%= f.text_field :home_phone %>
  </div>
  <div class="field">
    <%= f.label :work_phone %><br />
    <%= f.text_field :work_phone %>
  </div>
  <div class="field">
    <%= f.label :mobile_phone %><br />
    <%= f.text_field :mobile_phone %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Listing staffs</h1>

<table>
  <tr>
    <th>Salutation</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Suffix</th>
    <th>Address line1</th>
    <th>Address line2</th>
    <th>Address line3</th>
    <th>City</th>
    <th>State</th>
    <th>County</th>
    <th>Country</th>
    <th>Postal code</th>
    <th>Responder</th>
    <th>Dispatcher</th>
    <th>Case worker</th>
    <th>Home phone</th>
    <th>Work phone</th>
    <th>Mobile phone</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @staffs.each do |staff| %>
  <tr>
    <td><%= staff.salutation %></td>
    <td><%= staff.first_name %></td>
    <td><%= staff.last_name %></td>
    <td><%= staff.suffix %></td>
    <td><%= staff.address_line1 %></td>
    <td><%= staff.address_line2 %></td>
    <td><%= staff.address_line3 %></td>
    <td><%= staff.city %></td>
    <td><%= staff.state %></td>
    <td><%= staff.county %></td>
    <td><%= staff.country %></td>
    <td><%= staff.postal_code %></td>
    <td><%= staff.responder %></td>
    <td><%= staff.dispatcher %></td>
    <td><%= staff.case_worker %></td>
    <td><%= staff.home_phone %></td>
    <td><%= staff.work_phone %></td>
    <td><%= staff.mobile_phone %></td>
    <td><%= staff.latitude %></td>
    <td><%= staff.longitude %></td>
    <td><%= link_to 'Show', staff %></td>
    <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
    <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Salutation:</b>
  <%= @staff.salutation %>
</p>

<p>
  <b>First name:</b>
  <%= @staff.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @staff.last_name %>
</p>

<p>
  <b>Suffix:</b>
  <%= @staff.suffix %>
</p>

<p>
  <b>Address line1:</b>
  <%= @staff.address_line1 %>
</p>

<p>
  <b>Address line2:</b>
  <%= @staff.address_line2 %>
</p>

<p>
  <b>Address line3:</b>
  <%= @staff.address_line3 %>
</p>

<p>
  <b>City:</b>
  <%= @staff.city %>
</p>

<p>
  <b>State:</b>
  <%= @staff.state %>
</p>

<p>
  <b>County:</b>
  <%= @staff.county %>
</p>

<p>
  <b>Country:</b>
  <%= @staff.country %>
</p>

<p>
  <b>Postal code:</b>
  <%= @staff.postal_code %>
</p>

<p>
  <b>Responder:</b>
  <%= @staff.responder %>
</p>

<p>
  <b>Dispatcher:</b>
  <%= @staff.dispatcher %>
</p>

<p>
  <b>Case worker:</b>
  <%= @staff.case_worker %>
</p>

<p>
  <b>Home phone:</b>
  <%= @staff.home_phone %>
</p>

<p>
  <b>Work phone:</b>
  <%= @staff.work_phone %>
</p>

<p>
  <b>Mobile phone:</b>
  <%= @staff.mobile_phone %>
</p>

<p>
  <b>Latitude:</b>
  <%= @staff.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @staff.longitude %>
</p>


<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>