config/routes.rb
RedCross::Application.routes.draw do
  get "main/display"
  post "main/new"
  get "main/test"

  resources :stock_types

  resources :genders

  resources :notifying_agencies

  resources :incident_stock_types

  resources :ethnicities

  resources :economic_statuses

  resources :dwelling_types

  resources :disaster_types

  resources :staffs

  resources :incident_assistances

  resources :clients

  resources :incidents

  resources :incident_responders

  root :to => 'main#display'
  match 'main/new', :controller => "main", :action => "new", :as => "main_new"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :city, :county, :date_deceased, :date_of_birth, :economic_status_type_id, :ethnicity_type_id, :family_id, :first_name, :gender_type_id, :head_of_house_hold, :home_phone, :language_id, :last_name, :mobile_phone, :postal_code, :salutation, :state, :suffix, :work_phone
end

app/models/disaster_type.rb
class DisasterType < ActiveRecord::Base
  attr_accessible :name
end

app/models/dwelling_type.rb
class DwellingType < ActiveRecord::Base
  attr_accessible :name, :story
end

app/models/economic_status.rb
class EconomicStatus < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :cliend_id
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :type
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  attr_accessible :address_line1, :city, :county, :damange_assessment, :date_follow_up, :dispatcher_id, :dwelling_id, :events_sequence, :follow_up_result, :incident_date, :incident_time, :injuries_or_death, :memo_verification_info, :national_incident_id, :nbr_affected_families, :nbr_affected_individuals, :notification_agency_id, :notification_date, :notification_time, :person_following_up, :postal_code, :rc_chapter, :state, :trainee_follow_up, :trainee_name, :verification_agency, :verification_date, :verification_time
  # has_many :family, :incident_responder, :incident_client, :incident_disaster, :incident_assistance, :staff, :incident_stock_type
end

app/models/incident_client.rb
class IncidentClient < ActiveRecord::Base
  attr_accessible :family_id, :incident_id, :nine01_case_id
  belongs_to :incident
end

app/models/incident_disaster.rb
class IncidentDisaster < ActiveRecord::Base
  attr_accessible :disaster_type_id, :incident_id
  belongs_to :incident
end

app/models/incident_responder.rb
class IncidentResponder < ActiveRecord::Base
  attr_accessible :date_left_scene, :date_on_scene, :dispatched_date, :dispatched_time, :dispatcher_id, :incident_id, :initial_responder, :staff_id, :time_left_scene, :time_on_scene
  belongs_to :incident
end

app/models/notifying_agency.rb
class NotifyingAgency < ActiveRecord::Base
  attr_accessible :name
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :case_worker, :city, :country, :county, :dispatcher, :first_name, :home_phone, :last_name, :latitude, :longitude, :mobile_phone, :postal_code, :responder, :salutation, :state, :suffix, :work_phone
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  attr_accessible :name
  serialize :name, JSON
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def display
  end

  def new
    incident = create_incident
    create_incident_responder
    create_incident_assistance
    create_client
    render action:"display"
  end

  def create_incident
    Incident.create(
      notification_date: params[:notification_date],
      notification_time: params[:notification_time],
      notification_agency_id: params[:notification_agency_id],
      dispatcher_id: params[:dispatcher_id],
      address_line1: params[:address_line1],
      city: params[:city],
      state: params[:state],
      county: params[:county],
      postal_code: params[:postal_code],
      rc_chapter: params[:rc_chapter],
      verification_date: params[:verification_date],
      verification_time: params[:verification_time],
      verification_agency: params[:verification_agency],
      memo_verification_info: params[:memo_verification_info],
      incident_date: params[:incident_date],
      incident_time: params[:incident_time],
      nbr_affected_families: params[:nbr_affected_families],
      nbr_affected_individuals: params[:nbr_affected_individuals],
      events_sequence: params[:events_sequence],
      dwelling_id: params[:dwelling_id],
      damange_assessment: params[:damange_assessment],
      injuries_or_death: params[:injuries_or_death],
      national_incident_id: params[:national_incident_id],
      trainee_follow_up: params[:trainee_follow_up],
      date_follow_up: params[:date_follow_up],
      trainee_name: params[:trainee_name],
      person_following_up: params[:person_following_up],
      follow_up_result: params[:follow_up_result]
      # created_at: params[:created_at],
      # updated_at: params[:updated_at] 
      )              


  end

  def create_incident_responder

    IncidentResponder.create(
                             date_left_scene: params[:date_left_scene], #needs to be added to form
                             date_on_scene: params[:date_on_scene], #needs adding
                             dispatched_date: params[:dispatched_date], #needs adding
                             dispatched_time: params[:dispatched_time],
                             dispatcher_id: params[:dispatcher],
                             incident_id: params[:in], #needs adding
                             initial_responder: params[:initial_responder], #needs adding
                             staff_id: params[:staff_id], #needs adding
                             time_left_scene: params[:time_left_scene], #needs adding
                             time_on_scene: params[:time_on_scene] #needs adding
                             )

  end

  def create_incident_assistance

    IncidentAssistance.create(
                              addition_info: params[:additional_info],
                              case_number: params[:case_number], # name not in main page form
                              disaster_services_technology: params[:disaster_services_technology], # name not in main page form
                              family_id: params[:family_id], #not in form
                              health_services: params[:health_services], #in form as 'services', needs to be broken out
                              incident_id: params[:incident_id], #not on form
                              mass_care_service: params[:mass_care_service], #on form as "services", needs to broken out.
                              nbr_adult_receiving_assistance: params[:adults_serviced],
                              nbr_children_receiving_assistance: params[:children_service],
                              partner_services: params[:partner_services], #on form as "services", needs to be broken out
                              unit_floor: params[:unit_floor], #not in form
                              unserviced: params[:unserviced], #not in form
                              unserviced_reason: params[:unserviced] #not in form
                              )
  end

  def create_client
    Client.create(
      salutation: params[:salutation],
      first_name: params[:first_name],
      last_name: params[:last_name],
      suffix: params[:suffix],
      # address_line_one: params[:address_line_one],
      # address_line_two: params[:address_line_two],
      # address_line_three: params[:address_line_three],
      state: params[:state],
      county: params[:county],
      postal_code: params[:postal_code],
      home_phone: params[:home_phone],
      work_phone: params[:work_phone],
      mobile_phone: params[:mobile_phone],
      date_of_birth: params[:date_of_birth],
      date_deceased: params[:date_deceased],
      head_of_house_hold: params[:head_of_house_hold],
      ethnicity_type_id: params[:ethnicity_type_id],
      language_id: params[:language_id],
      gender_type_id: params[:gender_type_id],
      economic_status_type_id: params[:economic_status_type_id]
      # created_at: params[:created_at],
      # updated_at: params[:updated_at]
      )

  end

  def test

    render action:"test"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/ethnicities_helper.rb
module EthnicitiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/main/display.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">

        <link href="/assets/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="/assets/bootstrap-responsive.css" rel="stylesheet" type="text/css" />  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style>
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
       
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Test Form</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form pull-right">
                            <input class="span2" type="text" placeholder="Email">
                            <input class="span2" type="password" placeholder="Password">
                            <button type="submit" class="btn">Sign in</button>
                        </form>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <h2>DISASTER INCIDENT WORKSHEET</h2>
            </div>

            <!-- Example row of columns -->
            <div class="row">
                <div class="span6 offset3">
                    <form id="main_form" action="/main/new">
                        <p>Incident Responder:</p>
                        <input class="span5" name="dispatcher" placeholder="DISPATCHER:">
                        <input class="span5" name="initial_responder" placeholder="Initial Responder">
                        
                        <input class="span5" name="dispatched_date" placeholder="Dispatched Date">
                        <input class="span5" name="date_on_scene" placeholder="Date on scene">
                        <input class="span5" name="time_on_scene" placeholder="Time on scene">
                        <input class="span5" name="date_left_scene" placeholder="Date left scene">
                        <input class="span5" name="time_left_scene" placeholder="Date left scene">

                        <p>Client Info:</p>
                        <input class="span5 client" placeholder="salutation" name="salutation">
                        <input class="span5 client" placeholder="first_name" name="first_name">
                        <input class="span5 client" placeholder="middle_name" name="middle_name">
                        <input class="span5 client" placeholder="last_name" name="last_name">
                        <input class="span5 client" placeholder="suffix" name="suffix">
                        <input class="span5 client" placeholder="home_address" name="home_address">
                        <input class="span5 client" placeholder="city" name="city">
                        <input class="span5 client" placeholder="state" name="state">
                        <input class="span5 client" placeholder="county" name="county">
                        <input class="span5 client" placeholder="country" name="country">
                        <input class="span5 client" placeholder="home_phone_nbr" name="home_phone_nbr">
                        <input class="span5 client" placeholder="work_phone_nbr" name="work_phone_nbr">
                        <input class="span5 client" placeholder="mobile_phone_nbr" name="mobile_phone_nbr">
                        <input class="span5 client" placeholder="date_of_birth" name="date_of_birth">
                        <input class="span5 client" placeholder="date_deceased" name="date_deceased">
                        <input class="span5 client" placeholder="head_of_household" name="head_of_household">
                        <input class="span5 client" placeholder="ethnicitytypeid" name="ethnicitytypeid">
                        <input class="span5 client" placeholder="language" name="language">
                        <!-- <button id="add_member btn"><i class="icon-plus-sign"></i>Save and add new Family member</button> -->

                        <input class="span5" name="disaster_type" placeholder="TYPE OF DISASTER:">
                        <input class="span5" name="case_id" placeholder="CAS INCIDENT ID:">
                        <input class="span5" name="dispatcher_num" placeholder="DISASTER #:">
                        <input class="span5" name="dispatch_time" placeholder="DISPATCHED TIME:">
                        <input class="span5" name="arc_person" placeholder="ARC PERSON RECEIVING DISPATCH CALLTIME RESPONDERS ON SCENE:">
                        <input class="span5" name="time_left" placeholder="TIME RESPONDERS LEFT SCENE:">
                        <textarea class="span5" name="all_personel_responding" placeholder="NAMES AND PHONE NUMBERS ALL PERSONNEL RESPONDING(Mass Care, Health Services, DMH, etc.):"></textarea>
                        <input class="span5" name="" placeholder="SEQUENCEOF EVENTS">
                        <input class="span5" name"dwelling_type" placehoder="TYPE OF DWELLING:">
                        <textarea class="span5" name="damage_assesment" placeholder="DAMAGE ASSESSMENT(broken down by room/unit):"></textarea>
                        <input class="span5" name="adults_serviced" placeholder="NUMBER OF TOTAL ADULTS SERVICED:">
                        <input class="span5" name="children_serviced" placeholder="NUMBER OFTOTAL CHILDREN SERVICED:">
                        <textarea class="span5" name="injuries_fatalities" placeholder="ANY INJURIES OR DEATHS? (explain)LIST OF TENANTS (HEAD OF HOUSEHOLD ONLY)  / PHONE #/UNITS AFFECTED/LANDLORD INFO (if available):"></textarea>
                        <input class="span5" name="unserviced_clients" placeholder="UNSERVICED CLIENTS/UNITS AND WHYCAC # AND AMOUNTS PROVIDED:">
                        <input class="span5" name="stock_provided" placeholder="STOCK PROVIDED (Comfort Kits/PrePacks/Teddy Bears):">
                        <input class="span5" name="case_number_901" placeholder="CASE NUMBER FROM 901(s):">
                        <input class="span5" name="services" placeholder="MASS CARE SERVICES?HEALTH SERVICES?MENTAL HEALTH SERVICES?PARTNER SERVICES?DISASTER SERVICES TECHNOLOGY?">
                        <textarea class="span5" name="additional_info" placeholder="ANY ADDITIONAL INFO:"></textarea>
                        <input class="span5" name="total_cost" placeholder="Total cost">
                        <input class="span5" name="client_language" placeholder="Language of client">

                        <p>***FOR OFFICE USE ONLY***</p>
                        <p>TRAINEE FOLLOW UP</p>
                        <input name="date_followed_up" placeholder="DATE FOLLOWED UP">

                        <input class="span5" name="" placeholder="NAME OF PERSON DOING FOLLOW UP:">
                        <input class="span5" name="" placeholder="RESULT OF FOLLOW UP:">
                        <input class="span5" name="" placeholder="COORDINATOR CONFIRMED:">
                        <div class="form-actions">
                        <input class="btn span3 btn-primary" type="submit" id="submit" placeholder="submit">
                       <!--  <button type="submit" class="btn btn-primary">Save changes</button> -->
                        <button type="button" class="btn btn-danger">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>

            <hr>

        </div> <!-- /container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>


        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>



<h1><%=@name%></h1>

<ol>
  <li><%= link_to "stock types", stock_types_path%></li>
  <li><%= link_to "genders", genders_path%></li>
  <li><%= link_to "notifying agencies", notifying_agencies_path%></li>
  <li><%= link_to "incident stock types", incident_stock_types_path%></li>
  <li><%= link_to "ethnicities", ethnicities_path%></li>
  <li><%= link_to "economic statuses", economic_statuses_path%></li>
  <li><%= link_to "dwelling types", dwelling_types_path%></li>
  <li><%= link_to "disaster types", disaster_types_path%></li>
  <li><%= link_to "staffs", staffs_path%></li>
  <li><%= link_to "incident assistances", incident_assistances_path%></li>
  <li><%= link_to "clients", clients_path%></li>
  <li><%= link_to "incidents", incidents_path%></li>
  <li><%= link_to "incident responders", incident_responders_path%></li>
</ol>

app/views/main/test.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <style>
            body {
                padding-top: 60px;
                padding-bottom: 40px;
            }
        </style>
       
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->

        <!-- This code is taken from http://twitter.github.com/bootstrap/examples/hero.html -->

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Test Form</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <form class="navbar-form pull-right">
                            <input class="span2" type="text" placeholder="Email">
                            <input class="span2" type="password" placeholder="Password">
                            <button type="submit" class="btn">Sign in</button>
                        </form>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

            <!-- Main hero unit for a primary marketing message or call to action -->
            <div class="hero-unit">
                <h2>DISASTER INCIDENT WORKSHEET</h2>
            </div>

            <!-- Example row of columns -->
            <div class="row">
                <div class="span6 offset3">
                    <h3>Form</h3>
                    <form id="main_form" action="/main/new">
                        <input name="name" class="span5">
                        <input type="submit">
                    </form>
                </div>
            </div>

            <hr>

        </div> <!-- /container -->

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.9.1.min.js"><\/script>')</script>


        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>



<h1><%=@name%></h1>

<ol>
  <li><%= link_to "stock types", stock_types_path%></li>
  <li><%= link_to "genders", genders_path%></li>
  <li><%= link_to "notifying agencies", notifying_agencies_path%></li>
  <li><%= link_to "incident stock types", incident_stock_types_path%></li>
  <li><%= link_to "ethnicities", ethnicities_path%></li>
  <li><%= link_to "economic statuses", economic_statuses_path%></li>
  <li><%= link_to "dwelling types", dwelling_types_path%></li>
  <li><%= link_to "disaster types", disaster_types_path%></li>
  <li><%= link_to "staffs", staffs_path%></li>
  <li><%= link_to "incident assistances", incident_assistances_path%></li>
  <li><%= link_to "clients", clients_path%></li>
  <li><%= link_to "incidents", incidents_path%></li>
  <li><%= link_to "incident responders", incident_responders_path%></li>
</ol>