config/routes.rb
RedCross::Application.routes.draw do
  get "main/display"
  post "main/new"
  get "main/test"

  resources :stock_types

  resources :genders

  resources :notifying_agencies

  resources :incident_stock_types

  resources :ethnicities

  resources :economic_statuses

  resources :dwelling_types

  resources :disaster_types

  resources :staffs

  resources :incident_assistances

  resources :clients

  resources :incidents

  resources :incident_responders

  root :to => 'main#display'
  match 'main/new', :controller => "main", :action => "new", :as => "main_new"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :city, :county, :date_deceased, :date_of_birth, :economic_status_type_id, :ethnicity_type_id, :family_id, :first_name, :gender_type_id, :head_of_house_hold, :home_phone, :language_id, :last_name, :mobile_phone, :postal_code, :salutation, :state, :suffix, :work_phone
end

app/models/disaster_type.rb
class DisasterType < ActiveRecord::Base
  attr_accessible :name
end

app/models/dwelling_type.rb
class DwellingType < ActiveRecord::Base
  attr_accessible :name, :story
end

app/models/economic_status.rb
class EconomicStatus < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :cliend_id
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :type
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  attr_accessible :address_line1, :city, :county, :damange_assessment, :date_follow_up, :dispatcher_id, :dwelling_id, :events_sequence, :follow_up_result, :incident_date, :incident_time, :injuries_or_death, :memo_verification_info, :national_incident_id, :nbr_affected_families, :nbr_affected_individuals, :notification_agency_id, :notification_date, :notification_time, :person_following_up, :postal_code, :rc_chapter, :state, :trainee_follow_up, :trainee_name, :verification_agency, :verification_date, :verification_time
  # has_many :family, :incident_responder, :incident_client, :incident_disaster, :incident_assistance, :staff, :incident_stock_type
end

app/models/incident_client.rb
class IncidentClient < ActiveRecord::Base
  attr_accessible :family_id, :incident_id, :nine01_case_id
  belongs_to :incident
end

app/models/incident_disaster.rb
class IncidentDisaster < ActiveRecord::Base
  attr_accessible :disaster_type_id, :incident_id
  belongs_to :incident
end

app/models/incident_responder.rb
class IncidentResponder < ActiveRecord::Base
  attr_accessible :date_left_scene, :date_on_scene, :dispatched_date, :dispatched_time, :dispatcher_id, :incident_id, :initial_responder, :staff_id, :time_left_scene, :time_on_scene
  belongs_to :incident
end

app/models/notifying_agency.rb
class NotifyingAgency < ActiveRecord::Base
  attr_accessible :name
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :case_worker, :city, :country, :county, :dispatcher, :first_name, :home_phone, :last_name, :latitude, :longitude, :mobile_phone, :postal_code, :responder, :salutation, :state, :suffix, :work_phone
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  attr_accessible :name
  serialize :name, JSON
end

app/controllers/incident_responders_controller.rb
class IncidentRespondersController < ApplicationController
  # GET /incident_responders
  # GET /incident_responders.json
  def index
    @incident_responders = IncidentResponder.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incident_responders }
    end
  end

  # GET /incident_responders/1
  # GET /incident_responders/1.json
  def show
    @incident_responder = IncidentResponder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @incident_responder }
    end
  end

  # GET /incident_responders/new
  # GET /incident_responders/new.json
  def new
    @incident_responder = IncidentResponder.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incident_responder }
    end
  end

  # GET /incident_responders/1/edit
  def edit
    @incident_responder = IncidentResponder.find(params[:id])
  end

  # POST /incident_responders
  # POST /incident_responders.json
  def create
    @incident_responder = IncidentResponder.new(params[:incident_responder])

    respond_to do |format|
      if @incident_responder.save
        format.html { redirect_to @incident_responder, notice: 'Incident responder was successfully created.' }
        format.json { render json: @incident_responder, status: :created, location: @incident_responder }
      else
        format.html { render action: "new" }
        format.json { render json: @incident_responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incident_responders/1
  # PUT /incident_responders/1.json
  def update
    @incident_responder = IncidentResponder.find(params[:id])

    respond_to do |format|
      if @incident_responder.update_attributes(params[:incident_responder])
        format.html { redirect_to @incident_responder, notice: 'Incident responder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @incident_responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_responders/1
  # DELETE /incident_responders/1.json
  def destroy
    @incident_responder = IncidentResponder.find(params[:id])
    @incident_responder.destroy

    respond_to do |format|
      format.html { redirect_to incident_responders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/ethnicities_helper.rb
module EthnicitiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/incident_responders_helper.rb
module IncidentRespondersHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/incident_responders/_form.html.erb
<%= form_for(@incident_responder) do |f| %>
  <% if @incident_responder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident_responder.errors.count, "error") %> prohibited this incident_responder from being saved:</h2>

      <ul>
      <% @incident_responder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :incident_id %><br />
    <%= f.number_field :incident_id %>
  </div>
  <div class="field">
    <%= f.label :staff_id %><br />
    <%= f.number_field :staff_id %>
  </div>
  <div class="field">
    <%= f.label :dispatcher_id %><br />
    <%= f.number_field :dispatcher_id %>
  </div>
  <div class="field">
    <%= f.label :dispatched_date %><br />
    <%= f.date_select :dispatched_date %>
  </div>
  <div class="field">
    <%= f.label :dispatched_time %><br />
    <%= f.time_select :dispatched_time %>
  </div>
  <div class="field">
    <%= f.label :date_on_scene %><br />
    <%= f.date_select :date_on_scene %>
  </div>
  <div class="field">
    <%= f.label :time_on_scene %><br />
    <%= f.time_select :time_on_scene %>
  </div>
  <div class="field">
    <%= f.label :date_left_scene %><br />
    <%= f.date_select :date_left_scene %>
  </div>
  <div class="field">
    <%= f.label :time_left_scene %><br />
    <%= f.time_select :time_left_scene %>
  </div>
  <div class="field">
    <%= f.label :initial_responder %><br />
    <%= f.check_box :initial_responder %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incident_responders/edit.html.erb
<h1>Editing incident_responder</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident_responder %> |
<%= link_to 'Back', incident_responders_path %>

app/views/incident_responders/index.html.erb
<h1>Listing incident_responders</h1>

<table>
  <tr>
    <th>Incident</th>
    <th>Staff</th>
    <th>Dispatcher</th>
    <th>Dispatched date</th>
    <th>Dispatched time</th>
    <th>Date on scene</th>
    <th>Time on scene</th>
    <th>Date left scene</th>
    <th>Time left scene</th>
    <th>Initial responder</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @incident_responders.each do |incident_responder| %>
  <tr>
    <td><%= incident_responder.incident_id %></td>
    <td><%= incident_responder.staff_id %></td>
    <td><%= incident_responder.dispatcher_id %></td>
    <td><%= incident_responder.dispatched_date %></td>
    <td><%= incident_responder.dispatched_time %></td>
    <td><%= incident_responder.date_on_scene %></td>
    <td><%= incident_responder.time_on_scene %></td>
    <td><%= incident_responder.date_left_scene %></td>
    <td><%= incident_responder.time_left_scene %></td>
    <td><%= incident_responder.initial_responder %></td>
    <td><%= link_to 'Show', incident_responder %></td>
    <td><%= link_to 'Edit', edit_incident_responder_path(incident_responder) %></td>
    <td><%= link_to 'Destroy', incident_responder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Incident responder', new_incident_responder_path %>

app/views/incident_responders/new.html.erb
<h1>New incident_responder</h1>

<%= render 'form' %>

<%= link_to 'Back', incident_responders_path %>

app/views/incident_responders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Incident:</b>
  <%= @incident_responder.incident_id %>
</p>

<p>
  <b>Staff:</b>
  <%= @incident_responder.staff_id %>
</p>

<p>
  <b>Dispatcher:</b>
  <%= @incident_responder.dispatcher_id %>
</p>

<p>
  <b>Dispatched date:</b>
  <%= @incident_responder.dispatched_date %>
</p>

<p>
  <b>Dispatched time:</b>
  <%= @incident_responder.dispatched_time %>
</p>

<p>
  <b>Date on scene:</b>
  <%= @incident_responder.date_on_scene %>
</p>

<p>
  <b>Time on scene:</b>
  <%= @incident_responder.time_on_scene %>
</p>

<p>
  <b>Date left scene:</b>
  <%= @incident_responder.date_left_scene %>
</p>

<p>
  <b>Time left scene:</b>
  <%= @incident_responder.time_left_scene %>
</p>

<p>
  <b>Initial responder:</b>
  <%= @incident_responder.initial_responder %>
</p>


<%= link_to 'Edit', edit_incident_responder_path(@incident_responder) %> |
<%= link_to 'Back', incident_responders_path %>