config/routes.rb
RedCross::Application.routes.draw do
  get "main/display"
  post "main/new"
  get "main/test"

  resources :stock_types

  resources :genders

  resources :notifying_agencies

  resources :incident_stock_types

  resources :ethnicities

  resources :economic_statuses

  resources :dwelling_types

  resources :disaster_types

  resources :staffs

  resources :incident_assistances

  resources :clients

  resources :incidents

  resources :incident_responders

  root :to => 'main#display'
  match 'main/new', :controller => "main", :action => "new", :as => "main_new"

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :city, :county, :date_deceased, :date_of_birth, :economic_status_type_id, :ethnicity_type_id, :family_id, :first_name, :gender_type_id, :head_of_house_hold, :home_phone, :language_id, :last_name, :mobile_phone, :postal_code, :salutation, :state, :suffix, :work_phone
end

app/models/disaster_type.rb
class DisasterType < ActiveRecord::Base
  attr_accessible :name
end

app/models/dwelling_type.rb
class DwellingType < ActiveRecord::Base
  attr_accessible :name, :story
end

app/models/economic_status.rb
class EconomicStatus < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/ethnicity.rb
class Ethnicity < ActiveRecord::Base
  attr_accessible :type_name
end

app/models/family.rb
class Family < ActiveRecord::Base
  attr_accessible :cliend_id
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  attr_accessible :type
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  attr_accessible :address_line1, :city, :county, :damange_assessment, :date_follow_up, :dispatcher_id, :dwelling_id, :events_sequence, :follow_up_result, :incident_date, :incident_time, :injuries_or_death, :memo_verification_info, :national_incident_id, :nbr_affected_families, :nbr_affected_individuals, :notification_agency_id, :notification_date, :notification_time, :person_following_up, :postal_code, :rc_chapter, :state, :trainee_follow_up, :trainee_name, :verification_agency, :verification_date, :verification_time
  # has_many :family, :incident_responder, :incident_client, :incident_disaster, :incident_assistance, :staff, :incident_stock_type
end

app/models/incident_client.rb
class IncidentClient < ActiveRecord::Base
  attr_accessible :family_id, :incident_id, :nine01_case_id
  belongs_to :incident
end

app/models/incident_disaster.rb
class IncidentDisaster < ActiveRecord::Base
  attr_accessible :disaster_type_id, :incident_id
  belongs_to :incident
end

app/models/incident_responder.rb
class IncidentResponder < ActiveRecord::Base
  attr_accessible :date_left_scene, :date_on_scene, :dispatched_date, :dispatched_time, :dispatcher_id, :incident_id, :initial_responder, :staff_id, :time_left_scene, :time_on_scene
  belongs_to :incident
end

app/models/notifying_agency.rb
class NotifyingAgency < ActiveRecord::Base
  attr_accessible :name
end

app/models/staff.rb
class Staff < ActiveRecord::Base
  attr_accessible :address_line1, :address_line2, :address_line3, :case_worker, :city, :country, :county, :dispatcher, :first_name, :home_phone, :last_name, :latitude, :longitude, :mobile_phone, :postal_code, :responder, :salutation, :state, :suffix, :work_phone
end

app/models/stock_type.rb
class StockType < ActiveRecord::Base
  attr_accessible :name
  serialize :name, JSON
end

app/controllers/notifying_agencies_controller.rb
class NotifyingAgenciesController < ApplicationController
  # GET /notifying_agencies
  # GET /notifying_agencies.json
  def index
    @notifying_agencies = NotifyingAgency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifying_agencies }
    end
  end

  # GET /notifying_agencies/1
  # GET /notifying_agencies/1.json
  def show
    @notifying_agency = NotifyingAgency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notifying_agency }
    end
  end

  # GET /notifying_agencies/new
  # GET /notifying_agencies/new.json
  def new
    @notifying_agency = NotifyingAgency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notifying_agency }
    end
  end

  # GET /notifying_agencies/1/edit
  def edit
    @notifying_agency = NotifyingAgency.find(params[:id])
  end

  # POST /notifying_agencies
  # POST /notifying_agencies.json
  def create
    @notifying_agency = NotifyingAgency.new(params[:notifying_agency])

    respond_to do |format|
      if @notifying_agency.save
        format.html { redirect_to @notifying_agency, notice: 'Notifying agency was successfully created.' }
        format.json { render json: @notifying_agency, status: :created, location: @notifying_agency }
      else
        format.html { render action: "new" }
        format.json { render json: @notifying_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifying_agencies/1
  # PUT /notifying_agencies/1.json
  def update
    @notifying_agency = NotifyingAgency.find(params[:id])

    respond_to do |format|
      if @notifying_agency.update_attributes(params[:notifying_agency])
        format.html { redirect_to @notifying_agency, notice: 'Notifying agency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notifying_agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifying_agencies/1
  # DELETE /notifying_agencies/1.json
  def destroy
    @notifying_agency = NotifyingAgency.find(params[:id])
    @notifying_agency.destroy

    respond_to do |format|
      format.html { redirect_to notifying_agencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/ethnicities_helper.rb
module EthnicitiesHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/notifying_agencies_helper.rb
module NotifyingAgenciesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/notifying_agencies/_form.html.erb
<%= form_for(@notifying_agency) do |f| %>
  <% if @notifying_agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notifying_agency.errors.count, "error") %> prohibited this notifying_agency from being saved:</h2>

      <ul>
      <% @notifying_agency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifying_agencies/edit.html.erb
<h1>Editing notifying_agency</h1>

<%= render 'form' %>

<%= link_to 'Show', @notifying_agency %> |
<%= link_to 'Back', notifying_agencies_path %>

app/views/notifying_agencies/index.html.erb
<h1>Listing notifying_agencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifying_agencies.each do |notifying_agency| %>
  <tr>
    <td><%= notifying_agency.name %></td>
    <td><%= link_to 'Show', notifying_agency %></td>
    <td><%= link_to 'Edit', edit_notifying_agency_path(notifying_agency) %></td>
    <td><%= link_to 'Destroy', notifying_agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notifying agency', new_notifying_agency_path %>

app/views/notifying_agencies/new.html.erb
<h1>New notifying_agency</h1>

<%= render 'form' %>

<%= link_to 'Back', notifying_agencies_path %>

app/views/notifying_agencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @notifying_agency.name %>
</p>


<%= link_to 'Edit', edit_notifying_agency_path(@notifying_agency) %> |
<%= link_to 'Back', notifying_agencies_path %>